/**
 * Generate a deterministic, SPDX-grouped license report from the installed
 * dependency tree. Bundled into the `licenses-audit` action and run against the
 * consumer's checkout (cwd = repo root) after the action installs dependencies.
 *
 * Package-manager-agnostic: it walks `node_modules` and reads each package's
 * declared `license`/`licenses` field, so the report is identical whether
 * dependencies were installed by pnpm, npm, or bun. It shells out to no package
 * manager, has zero runtime dependencies, and never touches the network — the
 * output depends only on what a frozen-lockfile install put on disk, so it is
 * stable across machines and CI for a given lockfile (no paths or timestamps).
 *
 * The output path defaults to `LICENSES.md` and is overridable via the
 * `LICENSES_FILE` environment variable (the action passes its `licenses-file`
 * input). Run directly with `bun src/licenses-report.ts`.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { sep } from "node:path";

const nodeModulesDir = "node_modules";
const unknownLicense = "UNKNOWN";
const preamble =
  "> Generated by the licenses-audit action (licenses-report.ts). Do not edit by hand.";

/** A single dependency's resolved license, keyed for de-duplication. */
export interface LicenseRecord {
  name: string;
  version: string;
  license: string;
}

/** Read a property from a value that may not be an object, without asserting its shape. */
function readProperty(value: unknown, key: string): unknown {
  if (typeof value !== "object" || value === null) return undefined;
  return (value as Record<string, unknown>)[key];
}

/** Return the value when it is a non-empty string, else `undefined`. */
function asNonEmptyString(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

/**
 * Resolve a manifest's declared license to a single display string. Tolerates
 * the SPDX string form, the legacy `{ type }` object, and the legacy
 * `licenses: [{ type }]` array; returns `UNKNOWN` when none is present.
 */
export function normalizeLicense(manifest: unknown): string {
  const license = readProperty(manifest, "license");
  const direct = asNonEmptyString(license);
  if (direct) return direct;
  const legacyType = asNonEmptyString(readProperty(license, "type"));
  if (legacyType) return legacyType;
  const licenses = readProperty(manifest, "licenses");
  if (Array.isArray(licenses)) {
    const types = licenses
      .map((entry) => asNonEmptyString(readProperty(entry, "type")))
      .filter((type): type is string => type !== undefined);
    if (types.length > 0) return types.join(" OR ");
  }
  return unknownLicense;
}

/**
 * True when a `node_modules`-relative path is a package's own manifest —
 * `<pkg>/package.json` or `@scope/<pkg>/package.json`, optionally nested under a
 * deeper `node_modules` (npm hoisting, or the pnpm/bun virtual store). Rejects
 * manifests shipped inside a package's own subtree (test fixtures, bundled
 * examples), which are not installed dependencies.
 */
export function isPackageManifest(relativePath: string): boolean {
  const segments = relativePath.split(sep);
  if (segments.pop() !== "package.json") return false;
  const depth = segments.length;
  if (depth === 0) return false;
  if (depth === 1) return !segments[0].startsWith(".");
  const parent = segments[depth - 2];
  if (depth === 2 && parent.startsWith("@")) return true;
  if (parent === "node_modules") return true;
  return segments[depth - 3] === "node_modules" && parent.startsWith("@");
}

/** Render records as Markdown grouped by license, with both axes sorted. */
export function renderLicensesMarkdown(records: LicenseRecord[]): string {
  const groups = new Map<string, string[]>();
  for (const record of records) {
    const group = groups.get(record.license) ?? [];
    group.push(`${record.name}@${record.version}`);
    groups.set(record.license, group);
  }
  const licenses = [...groups.keys()].sort();
  const sections = licenses.map((license) => {
    const bullets = (groups.get(license) ?? [])
      .slice()
      .sort()
      .map((entry) => `- ${entry}`)
      .join("\n");
    return `## ${license}\n\n${bullets}`;
  });
  const summary = `${records.length} packages across ${licenses.length} licenses.`;
  return `# Licenses\n\n${preamble}\n\n${summary}\n\n${sections.join("\n\n")}\n`;
}

/** Parse one manifest leniently; `null` when it is unreadable. */
async function readManifest(path: string): Promise<unknown> {
  try {
    return JSON.parse(await readFile(path, "utf8"));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`licenses-report: skipping ${path}: ${message}`);
    return null;
  }
}

/**
 * Walk `node_modules` and collect one record per distinct `name@version`,
 * skipping private packages (the consumer's own workspace members and anything
 * not published).
 */
async function collectRecords(directory: string): Promise<LicenseRecord[]> {
  const entries = await readdir(directory, { recursive: true });
  const records = new Map<string, LicenseRecord>();
  for (const entry of entries) {
    if (!isPackageManifest(entry)) continue;
    const manifest = await readManifest(`${directory}${sep}${entry}`);
    if (!manifest) continue;
    const name = asNonEmptyString(readProperty(manifest, "name"));
    const version = asNonEmptyString(readProperty(manifest, "version"));
    if (!name || !version || readProperty(manifest, "private") === true) continue;
    records.set(`${name}@${version}`, { name, version, license: normalizeLicense(manifest) });
  }
  return [...records.values()];
}

async function main(): Promise<void> {
  const outputFile = process.env.LICENSES_FILE ?? "LICENSES.md";
  const records = await collectRecords(nodeModulesDir);
  await writeFile(outputFile, renderLicensesMarkdown(records));
  console.log(`licenses-report: wrote ${outputFile} (${records.length} packages)`);
}

if (import.meta.main) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
